version: "2"
services:
  app:
    image: lhmun/uniqlyreviews_app
    container_name: uniqlyreviews_app
    ports:
      - "3005:3005"
    depends_on:
      - 'mongo'
  mongo:
    container_name: mongo
    image: mongo:latest
